controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_questions_by_category:
    path: '/questions/{id}'
    controller: 'App\Controller\QuizController::questionsByCategory'

